### PR TITLE
Seed database

### PR DESCRIPTION
**Pull request by fidellim**
# Description

Add 100 comments, users, and items to database

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
That was fast! I'll review the changes right away.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - I have no idea why, but I've been told that we are not allowed to update "docker-compose.yml". Please make sure to revert your changes before merging your PR.

**Review by vanessa-cooper — APPROVED** [review]
Nice! Looks like there are some records in your local DB. Now you can **merge the PR** and come **back to Snack** once you’re ready.

**Comment by fidellim** [comment]
Great!

**Pull request merged**
